### ISSUE TITLE
use-page composable is missing from sources

### ISSUE THREAD

**Issue by willybrauner** [rezozero/nuxt-starter#21]
https://github.com/rezozero/nuxt-starter/blob/530ed91e97525513c2af5cc055a8381aa3cea55d/composables/use-current-page.ts#L1C1-L1C51

**Comment by manuelodelain** [comment]
Resolved by https://github.com/rezozero/nuxt-starter/commit/56761e45608b0ecc90d4124f3931aa44cca37ba2
