### ISSUE TITLE
Update tasks

### ISSUE THREAD

**Issue by manuelodelain** [rezozero/nuxt-starter#24]
## Components

- [x] `VIcon`
- [x] `VButton`
- [x] `VRoadizVideo`
- [x] `VRoadizMedia`
- [x] `VLink`
- [x] `VButtonLink`
- [x] `VForm` + components
- [x] `VRoadizBlockFactory` & `VBlock`
- [x] `VModal`
- [x] `VChip`
- [x] `VTag`
- [x] `VCarousel`

### Composables

- [x] `useTopBarScroll`
- [x] `useLoadMore`
- [x] `useRoadizDocumentUrl` (previously `useDocumentUrl`)
- [x] `useHomePage`
- [x] `useHydraCollectionFetch`
- [x] `usePage` / `useCurrentPage` / `useNextPage` -> https://github.com/rezozero/nuxt-starter/issues/21
- [x] `useCacheTags`

**Comment by timothejoubert** [comment]
- [ ] Create a carousel component which dispatch native slider (VSlider) or swiper carousel depending on carousel functionality
