### ISSUE TITLE
VForm(VFieldWrapper): mismatch rendering element during hydratation

### ISSUE THREAD

**Issue by timothejoubert** [rezozero/nuxt-starter#59]
<img width="676" alt="image" src="https://github.com/user-attachments/assets/caa2c040-de44-45f5-aa3d-63c0942bdb93">

Happens only on server rendering, and can be replicated on stories as well.

**Comment by manuelodelain** [comment]
I don't reproduce the issue.

**Comment by timothejoubert** [comment]
Problem came from dashlane chrome plugin ext.
<img width="423" alt="image" src="https://github.com/user-attachments/assets/eb7e50fc-dbd2-405f-ac38-af41c9c0a555">
