### ISSUE TITLE
Wrong access to runtimeConfig value in useWebResponseCacheControl

### ISSUE THREAD

**Issue by timothejoubert** [rezozero/nuxt-starter#65]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/70833b1c-5d15-4cf0-97a9-a447650fbbbb">
<img width="552" alt="image" src="https://github.com/user-attachments/assets/49607d97-c0f9-4bd1-b03d-9469bab21734">

``` js
// Change to 
const cacheControlConfig = useRuntimeConfig().public.cacheControl
```

**Comment by timothejoubert** [comment]
I didn't check if the composable work but I suppose it doesn't

**Comment by manuelodelain** [comment]
closed by https://github.com/rezozero/nuxt-starter/pull/75
