### ISSUE TITLE
Legacy JS API is deprecated for sass

### ISSUE THREAD

**Issue by Illawind** [rezozero/nuxt-starter#66]
<img width="658" alt="image" src="https://github.com/user-attachments/assets/e88646da-17be-437d-bbbc-854b116eac69">

Potential solution : 
use `api: 'modern'` in vite.css.preprocessorOptions.scss in nuxt.config.ts
Source :
https://github.com/vitejs/vite/pull/17728

But warning for sourcemap :
```
Sourcemap for "{PERSONAL_FOLDERS}/frontend/assets/scss/main.scss" points to missing source files   
Sourcemap for "{PERSONAL_FOLDERS}/frontend/assets/scss/export/_breakpoints.module.scss" points to missing source files
```

**Comment by manuelodelain** [comment]
fixed by https://github.com/rezozero/nuxt-starter/pull/68
